name: eams-seof

channels:
  - conda-forge

dependencies:
  - python=3.10

  - numpy<2
  - pandas
  - xarray
  - scipy
  - astropy
  - netcdf4
  - bottleneck
  - dask
  - pyyaml

  - matplotlib=3.4.3
  - matplotlib-inline=0.1.7
  - proplot=0.9.7
  - cartopy
  - geopandas
  - shapely

  - jupyterlab
  - ipykernel

  - pytest

  - setuptools<82

  - pip
  - pip:
      - cmaps
